# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('friends_app', '0002_auto_20170725_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(to='login_app.User'),
        ),
    ]
