# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20170725_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
